
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ms-config-client-2244-test    # 防止 Eureka web页面报错 ，主机服务名称修改
    prefer-ip-address: true                  # 访问路径可以显示IP地址，（左下角IP显示）
info:
  app.name: ms-config-client-2244-test
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$